[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "./run.sh"
rustflags = ["-C", "panic=abort"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
